
-------------------
-- Primary Key
-------------------

-- Uniquely identify each record in the table

CREATE TABLE employee(
    emp_id INT PRIMARY KEY,
    firstname VARCHAR(20) NOT NULL,
    middlename VARCHAR(20),
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    salary INT NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'bangalore'
);

-- or

CREATE TABLE employee(
    emp_id INT,
    firstname VARCHAR(20) NOT NULL,
    middlename VARCHAR(20),
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    salary INT NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'bangalore',
    PRIMARY KEY(emp_id)
);


CREATE TABLE employee(
    emp_id INT,
    firstname VARCHAR(20) NOT NULL,
    middlename VARCHAR(20),
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    salary INT NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'bangalore',
    PRIMARY KEY(emp_id,firstname)
);

-- composite primary key on the basis of two number


INSERT INTO employee 
(emp_id,firstname,middlename,lastname,age,salary,location) 
VALUES (1,'ram','kumar','sharma',27,50000,'bangalore');


-- for a primary key NUll is not allowerd and repeated values are not allowed


-- Auto increatment

CREATE TABLE employee(
    emp_id INT AUTO_INCREMENT,
    firstname VARCHAR(20) NOT NULL,
    middlename VARCHAR(20),
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    salary INT NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'bangalore',
    PRIMARY KEY(emp_id)
);

---- Below is working sql for postges

CREATE TABLE employees(
    emp_id INT GENERATED BY DEFAULT AS IDENTITY,
    firstname VARCHAR(20) NOT NULL,
    middlename VARCHAR(20),
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    salary INT NOT NULL,
    location VARCHAR(20) NOT NULL DEFAULT 'bangalore',
    PRIMARY KEY(emp_id)
);




-------------------------------------------------------------------------


---------------
-- Unique Key
---------------

-- You can have only primary key
-- and the primary key cannot hold and NULL

-- We should use primary key when we have to uniquely identify each record.

-- Unique key can hold NULL

-- For example in Mysql a unique key can hold any number of NULL values

-- In some of the other famous DB's unique key hold only one Null


-- The Purpose of unique key is to make sure the values do not duplicate



-- Example of Primary Key
-- emp_id


-- Example of Unique Key
-- emp e-mail id


-- We can we have only one primary key but multiple unique keys in a table



-----------------------------------------

CREATE TABLE employee(
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY(firstname,lastname)
);


INSERT INTO employees VALUES ('Kumar','Omkar',20);
INSERT INTO employees VALUES ('Kumar','Omkar',20);

-- run twice will not work
-----------------------------------------



-----------------------------------------

CREATE TABLE employee(
    emp_id INT UNIQUE KEY
    firstname VARCHAR(20),
    lastname VARCHAR(20),
    age INT NOT NULL,
    UNIQUE KEY(firstname,lastname)
);


CREATE TABLE employee(
    firstname VARCHAR(20),
    lastname VARCHAR(20),
    age INT NOT NULL,
    UNIQUE KEY(firstname,lastname)
);


